const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
class V {constructor(x=0,y=0,z=0){Object.assign(this,{x,y,z});}set(x,y,z){Object.assign(this,{x,y,z});return this;}clone(){return new V(this.x,this.y,this.z);}add(v){this.x+=v.x;this.y+=v.y;this.z+=v.z;return this;}}
const elements=new Map(),listeners={};
function element(id){if(!elements.has(id))elements.set(id,{value:'',hidden:false,options:[],addEventListener(){},setPointerCapture(){},replaceChildren(){this.options=[];},appendChild(o){this.options.push(o);},click(){}});return elements.get(id);}
const ctx={console,THREE:{Vector3:V,Vector2:V},model(){},mk(){},draw(){},tab(){ctx.is3=true;},fitView(){},size(){},cl:(n,a,b)=>Math.min(b,Math.max(a,n)),is3:true,viewFloors:'all',floorHeight:3,PL:{w:10,l:10},plotVertices:[],PlotGeometry:{points:()=>[],contains:(_,p)=>p.x>=0&&p.y>=0&&p.x<=10&&p.y<=10},rooms:[{id:1,t:'living',x:1,y:1,w:4,l:4,floor:'#ffffff',fk:'tile'}],items:[{t:'sofa'},{t:'cabinet'},{t:'plant'}],RT:{living:{n:'Living'}},WALL:'#ffffff',save(){ctx.saves++;},saves:0,message(){},confirm:()=>true,render(){},build(){},requestAnimationFrame:()=>++ctx.frames,cancelAnimationFrame:()=>ctx.cancels++,frames:0,cancels:0,$:element,addEventListener:(name,fn)=>listeners[name]=fn,document:{addEventListener(){},querySelectorAll:()=>[],querySelector:()=>element('stage'),createElement:()=>({}),hidden:false},controls:{enabled:true,target:new V(),update(){}},cam:{position:new V(),fov:45,aspect:1,updateProjectionMatrix(){},lookAt(){}},renderer:{getSize:()=>new V(800,600),getPixelRatio:()=>2,setPixelRatio(v){ctx.pixelRatio=v;},setSize(w,h){ctx.outputSize=[w,h];},domElement:{toDataURL:()=>{throw Error('export unavailable');}}}};
vm.createContext(ctx);vm.runInContext(fs.readFileSync('interior.js','utf8'),ctx);
vm.runInContext('startWalking()',ctx);assert.equal(ctx.controls.enabled,false);assert.equal(ctx.cam.position.y,1.6);assert.equal(ctx.viewFloors,'active');assert.equal(element('walk-controls').hidden,false);
const initialZ=ctx.cam.position.z;listeners.keydown({key:'w',target:{tagName:'BUTTON'},preventDefault(){}});vm.runInContext('walkTick(100);walkTick(150)',ctx);assert.ok(ctx.cam.position.z<initialZ,'keyboard works after clicking the walk button');
const before=ctx.cam.position.z;listeners.keydown({key:'s',target:{tagName:'INPUT'},preventDefault(){throw Error('typing intercepted');}});vm.runInContext('held.clear();walkTick(200)',ctx);assert.equal(ctx.cam.position.z,before);
vm.runInContext('cam.position.set(0,1.6,0);held.add("forward");walkTick(250)',ctx);assert.equal(ctx.cam.position.z,0,'plot boundary prevents leaving the plot');
const cancelled=ctx.cancels;vm.runInContext('startWalking()',ctx);assert.equal(ctx.cancels,cancelled+1,'room jumps cancel the old animation frame');vm.runInContext('stopWalking()',ctx);assert.equal(ctx.controls.enabled,true);assert.equal(element('walk-controls').hidden,true);
element('interior-style').value='warm';element('apply-interior-style').onclick();assert.equal(ctx.WALL,'#f2efe8');assert.equal(ctx.rooms[0].fk,'wood');assert.equal(ctx.items[0].col,'#c9bca8');assert.equal(ctx.items[1].col,'#805d3e');assert.equal(ctx.items[2].col,undefined);assert.equal(ctx.saves,1);
element('save-interior-image').onclick();assert.deepEqual(ctx.outputSize,[800,600]);assert.equal(ctx.pixelRatio,2);assert.equal(ctx.cam.aspect,1,'failed export restores the viewport');
console.log('Walkthrough keyboard, room jumps, plot bounds, stop cleanup, style finishes and failed image-export recovery passed.');
